/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3 */

#include "downlink-messages/messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(downlink_proto_digitalMetrics, downlink_proto_digitalMetrics, AUTO)


PB_BIND(downlink_proto_analogMetrics, downlink_proto_analogMetrics, AUTO)


PB_BIND(downlink_proto_Timestamp, downlink_proto_Timestamp, AUTO)


PB_BIND(downlink_proto_PowerSupplyMetrics, downlink_proto_PowerSupplyMetrics, AUTO)


PB_BIND(downlink_proto_IMUMetrics, downlink_proto_IMUMetrics, AUTO)


PB_BIND(downlink_proto_SpaceComputerMetrics, downlink_proto_SpaceComputerMetrics, AUTO)


PB_BIND(downlink_proto_SystemMetrics, downlink_proto_SystemMetrics, AUTO)


PB_BIND(downlink_proto_DownlinkMessage, downlink_proto_DownlinkMessage, AUTO)



